const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/photon_stage.html','utf8'),src=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const elements={},defaults={a:'.5',b:'-.25',c:'.25',phase:String(Math.PI/2),analyzer:'0',eta:'1',k:'1',prep:'H'};
const ranges={a:[-10,10],b:[-10,10],c:[-10,10],phase:[-6.284,6.284],analyzer:[-6.284,6.284],eta:[0,1],k:[-100,100]};
for(const [id,value] of Object.entries(defaults))elements[id]={value,min:String(ranges[id]?.[0]??0),max:String(ranges[id]?.[1]??1)};
const context=vm.createContext({document:{getElementById:id=>elements[id]??=( {textContent:'',innerHTML:''})},setInterval:()=>1,clearInterval:()=>{},setTimeout,Math});vm.runInContext(src,context);
const run=s=>vm.runInContext(s,context),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-10,`${a} != ${b}`);
near(run('probability(rotate([1,0,0,0],Math.PI))[1]'),1);
near(run('probability(rotate([1,0,0,0],Math.PI/2))[0]'),.5);
near(run('probability(rotate(rotate([1,0,0,0],1.23),-1.23))[0]'),1);
near(run('probability(rotate(phaseGate(rotate([1,0,0,0],Math.PI/2),Math.PI),-Math.PI/2))[1]'),1);
near(run('probability(rotate(phaseGate(rotate([1,0,0,0],Math.PI/2),0),-Math.PI/2))[0]'),1);
for(let i=0;i<1000;i++)near(run(`probability(phaseGate(rotate(prepare('R'),${i/17}),${i/13})).reduce((a,b)=>a+b)`),1);
assert.equal(run('measure([1,0,0,0],0,()=>0.5)'),'LOST');
assert.equal(run('measure([1,0,0,0],1,()=>0.5)'),'H');
assert.equal(run('measure([0,0,1,0],1,()=>0.5)'),'V');
run("$('batch').onclick()");assert.equal(run('S.counts.H+S.counts.V+S.counts.LOST'),1000);
run("$('a').value='1';$('a').oninput()");assert.equal(run('S.counts.H+S.counts.V+S.counts.LOST'),0);
run("$('k').value='0';$('k').oninput()");near(run('probability(rows.at(-1).s)[0]'),1);
run("$('eta').value='';$('eta').oninput()");assert.equal(run('P'),null);assert.ok(elements.error.textContent);
run("$('eta').value='1';$('eta').oninput()");assert.ok(run('P'));
run("$('clear').onclick();for(let i=0;i<6;i++)step()");assert.equal(run('S.counts.H+S.counts.V+S.counts.LOST'),1);assert.equal(run('S.index'),6);
run('step()');assert.equal(run('S.index'),0);
console.log('PASS: rotations, cancellation, phase interference, 1000 norm cases, measurement/loss, batch/reset, invalid input, stage cycle.');
